[features]
seeds = false
skip-lint = false

[programs.devnet]
# solana_nft_anchor = "Bm67ZPNDQyCAi2izVu8ZfLqjqToZ4v39j9hEEYN96E9W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
